/********************************************************************************
** Form generated from reading UI file 'mainwindow_og.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_OG_H
#define UI_MAINWINDOW_OG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *label_20;
    QLabel *label_67;
    QLabel *label_64;
    QLabel *label_19;
    QLCDNumber *trialNo;
    QLabel *label_23;
    QLCDNumber *DesZ0;
    QRadioButton *VRControl;
    QLabel *label_21;
    QLabel *label_24;
    QLabel *label_59;
    QLabel *label;
    QPushButton *dynamicEnvironment;
    QLCDNumber *lcdNumberHapticRate;
    QPushButton *turnOff;
    QLCDNumber *DesY0;
    QLabel *label_69;
    QLabel *label_22;
    QLCDNumber *DesX1;
    QLCDNumber *DesZ1;
    QLCDNumber *DesY1;
    QLCDNumber *DesX0;
    QWidget *placeHolder;
    QWidget *widget;
    QLabel *label_34;
    QLabel *label_12;
    QLabel *label_33;
    QLCDNumber *CD_Val;
    QLCDNumber *Mass_Val;
    QLCDNumber *Inertia_Val;
    QLCDNumber *lcdNumberGraphicsRate;
    QLabel *label_31;
    QCheckBox *JakeRenderCheckBox;
    QLabel *label_11;
    QLineEdit *inertiaValue;
    QLabel *label_32;
    QLineEdit *cd_ratio;
    QCheckBox *CD_Vertical_Box;
    QPushButton *StiffnessExp;
    QLabel *label_35;
    QLineEdit *mass_set;
    QLCDNumber *MotorLCD_1;
    QLCDNumber *StrokeLCD1_1;
    QLabel *label_27;
    QLCDNumber *StrokeLCD1_0;
    QLabel *label_26;
    QLCDNumber *MotorLCD_0;
    QLCDNumber *pairNo;
    QLabel *label_49;
    QLabel *label_50;
    QCheckBox *equalBoxTouch;
    QLabel *label_14;
    QLCDNumber *stiff1Scale_show;
    QRadioButton *reverseBox;
    QLabel *label_51;
    QSpinBox *subject_no;
    QLCDNumber *stiff2Scale_show;
    QTextBrowser *text;
    QLCDNumber *Act1_show;
    QLCDNumber *Act2_show;
    QSlider *Act2;
    QLabel *label_54;
    QSlider *Act1;
    QLabel *label_55;
    QLCDNumber *ForZ0;
    QLCDNumber *ForY0;
    QLCDNumber *ForX0;
    QPushButton *Manual;
    QLCDNumber *direction;
    QLCDNumber *ForY1;
    QLCDNumber *ForX1;
    QLCDNumber *ForZ1;
    QLabel *label_52;
    QLabel *label_53;
    QLCDNumber *ForY0_2;
    QLCDNumber *ForX0_2;
    QLCDNumber *ForX1_2;
    QLCDNumber *ForZ0_2;
    QLCDNumber *ForZ1_2;
    QLCDNumber *ForY1_2;
    QLCDNumber *mass1_show;
    QLCDNumber *mass2_show;
    QRadioButton *equalBox;
    QPushButton *StiffnMassCombined;
    QSpinBox *SetTrialNo;
    QLabel *label_56;
    QCheckBox *AdjustTrialNo;
    QPushButton *FingerMappingExp;
    QLabel *label_57;
    QLabel *label_58;
    QRadioButton *Condition1;
    QLCDNumber *condition;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_15;
    QLabel *label_25;
    QTextBrowser *mappingTextBox;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(2300, 743);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(165, 165, 165, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(248, 248, 248, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(206, 206, 206, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(82, 82, 82, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(110, 110, 110, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(210, 210, 210, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        MainWindow->setPalette(palette);
        QFont font;
        font.setPointSize(12);
        MainWindow->setFont(font);
        QIcon icon;
        icon.addFile(QStringLiteral("D:/Pictures/Icon.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        MainWindow->setAutoFillBackground(true);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(1210, 190, 61, 21));
        label_67 = new QLabel(centralWidget);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(1460, 190, 61, 21));
        label_64 = new QLabel(centralWidget);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(1390, 190, 61, 21));
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(1140, 190, 61, 21));
        trialNo = new QLCDNumber(centralWidget);
        trialNo->setObjectName(QStringLiteral("trialNo"));
        trialNo->setGeometry(QRect(1630, 290, 61, 41));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Light, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        trialNo->setPalette(palette1);
        QFont font1;
        font1.setPointSize(14);
        font1.setBold(true);
        trialNo->setFont(font1);
        trialNo->setAutoFillBackground(false);
        trialNo->setLineWidth(1);
        trialNo->setMidLineWidth(0);
        trialNo->setDigitCount(3);
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(1630, 249, 101, 41));
        DesZ0 = new QLCDNumber(centralWidget);
        DesZ0->setObjectName(QStringLiteral("DesZ0"));
        DesZ0->setGeometry(QRect(1280, 220, 64, 23));
        DesZ0->setDigitCount(6);
        VRControl = new QRadioButton(centralWidget);
        VRControl->setObjectName(QStringLiteral("VRControl"));
        VRControl->setGeometry(QRect(2120, 530, 111, 61));
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(1280, 190, 61, 21));
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(1750, 250, 81, 41));
        label_59 = new QLabel(centralWidget);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(1390, 255, 91, 21));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(1140, 255, 111, 21));
        dynamicEnvironment = new QPushButton(centralWidget);
        dynamicEnvironment->setObjectName(QStringLiteral("dynamicEnvironment"));
        dynamicEnvironment->setGeometry(QRect(1880, 10, 181, 91));
        lcdNumberHapticRate = new QLCDNumber(centralWidget);
        lcdNumberHapticRate->setObjectName(QStringLiteral("lcdNumberHapticRate"));
        lcdNumberHapticRate->setGeometry(QRect(1750, 120, 71, 31));
        lcdNumberHapticRate->setDigitCount(7);
        turnOff = new QPushButton(centralWidget);
        turnOff->setObjectName(QStringLiteral("turnOff"));
        turnOff->setGeometry(QRect(1900, 540, 121, 51));
        DesY0 = new QLCDNumber(centralWidget);
        DesY0->setObjectName(QStringLiteral("DesY0"));
        DesY0->setGeometry(QRect(1210, 220, 64, 23));
        DesY0->setDigitCount(6);
        label_69 = new QLabel(centralWidget);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(1530, 190, 61, 21));
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(1750, 50, 121, 61));
        DesX1 = new QLCDNumber(centralWidget);
        DesX1->setObjectName(QStringLiteral("DesX1"));
        DesX1->setGeometry(QRect(1390, 220, 64, 23));
        DesX1->setDigitCount(6);
        DesZ1 = new QLCDNumber(centralWidget);
        DesZ1->setObjectName(QStringLiteral("DesZ1"));
        DesZ1->setGeometry(QRect(1530, 220, 64, 23));
        DesZ1->setDigitCount(6);
        DesY1 = new QLCDNumber(centralWidget);
        DesY1->setObjectName(QStringLiteral("DesY1"));
        DesY1->setGeometry(QRect(1460, 220, 64, 23));
        DesY1->setDigitCount(6);
        DesX0 = new QLCDNumber(centralWidget);
        DesX0->setObjectName(QStringLiteral("DesX0"));
        DesX0->setGeometry(QRect(1140, 220, 64, 23));
        DesX0->setDigitCount(6);
        placeHolder = new QWidget(centralWidget);
        placeHolder->setObjectName(QStringLiteral("placeHolder"));
        placeHolder->setGeometry(QRect(0, 0, 100, 30));
        widget = new QWidget(centralWidget);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(1449, 570, 261, 81));
        widget->setAutoFillBackground(false);
        label_34 = new QLabel(widget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 5, 81, 21));
        label_34->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_12 = new QLabel(widget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(180, 5, 61, 21));
        label_12->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_33 = new QLabel(widget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(100, 5, 61, 21));
        label_33->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        CD_Val = new QLCDNumber(widget);
        CD_Val->setObjectName(QStringLiteral("CD_Val"));
        CD_Val->setGeometry(QRect(100, 30, 64, 41));
        CD_Val->setDigitCount(3);
        Mass_Val = new QLCDNumber(widget);
        Mass_Val->setObjectName(QStringLiteral("Mass_Val"));
        Mass_Val->setGeometry(QRect(180, 30, 61, 41));
        Mass_Val->setDigitCount(5);
        Inertia_Val = new QLCDNumber(widget);
        Inertia_Val->setObjectName(QStringLiteral("Inertia_Val"));
        Inertia_Val->setGeometry(QRect(10, 30, 64, 41));
        Inertia_Val->setDigitCount(3);
        lcdNumberGraphicsRate = new QLCDNumber(centralWidget);
        lcdNumberGraphicsRate->setObjectName(QStringLiteral("lcdNumberGraphicsRate"));
        lcdNumberGraphicsRate->setGeometry(QRect(1640, 120, 81, 31));
        lcdNumberGraphicsRate->setDigitCount(7);
        label_31 = new QLabel(centralWidget);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(1640, 50, 101, 61));
        JakeRenderCheckBox = new QCheckBox(centralWidget);
        JakeRenderCheckBox->setObjectName(QStringLiteral("JakeRenderCheckBox"));
        JakeRenderCheckBox->setGeometry(QRect(1920, 600, 181, 31));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(2120, 420, 131, 71));
        inertiaValue = new QLineEdit(centralWidget);
        inertiaValue->setObjectName(QStringLiteral("inertiaValue"));
        inertiaValue->setGeometry(QRect(2120, 490, 71, 31));
        label_32 = new QLabel(centralWidget);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(2120, 350, 121, 31));
        cd_ratio = new QLineEdit(centralWidget);
        cd_ratio->setObjectName(QStringLiteral("cd_ratio"));
        cd_ratio->setGeometry(QRect(2120, 380, 71, 31));
        CD_Vertical_Box = new QCheckBox(centralWidget);
        CD_Vertical_Box->setObjectName(QStringLiteral("CD_Vertical_Box"));
        CD_Vertical_Box->setGeometry(QRect(1920, 660, 171, 31));
        StiffnessExp = new QPushButton(centralWidget);
        StiffnessExp->setObjectName(QStringLiteral("StiffnessExp"));
        StiffnessExp->setGeometry(QRect(1880, 120, 181, 91));
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(2120, 280, 111, 31));
        mass_set = new QLineEdit(centralWidget);
        mass_set->setObjectName(QStringLiteral("mass_set"));
        mass_set->setGeometry(QRect(2120, 310, 71, 31));
        MotorLCD_1 = new QLCDNumber(centralWidget);
        MotorLCD_1->setObjectName(QStringLiteral("MotorLCD_1"));
        MotorLCD_1->setGeometry(QRect(1390, 290, 64, 23));
        MotorLCD_1->setDigitCount(6);
        StrokeLCD1_1 = new QLCDNumber(centralWidget);
        StrokeLCD1_1->setObjectName(QStringLiteral("StrokeLCD1_1"));
        StrokeLCD1_1->setGeometry(QRect(1390, 350, 64, 23));
        StrokeLCD1_1->setDigitCount(6);
        label_27 = new QLabel(centralWidget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(1390, 325, 81, 21));
        StrokeLCD1_0 = new QLCDNumber(centralWidget);
        StrokeLCD1_0->setObjectName(QStringLiteral("StrokeLCD1_0"));
        StrokeLCD1_0->setGeometry(QRect(1140, 350, 64, 23));
        StrokeLCD1_0->setDigitCount(6);
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(1140, 325, 81, 21));
        MotorLCD_0 = new QLCDNumber(centralWidget);
        MotorLCD_0->setObjectName(QStringLiteral("MotorLCD_0"));
        MotorLCD_0->setGeometry(QRect(1140, 290, 64, 23));
        MotorLCD_0->setDigitCount(6);
        pairNo = new QLCDNumber(centralWidget);
        pairNo->setObjectName(QStringLiteral("pairNo"));
        pairNo->setGeometry(QRect(1750, 290, 81, 41));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Light, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pairNo->setPalette(palette2);
        QFont font2;
        font2.setPointSize(16);
        font2.setBold(true);
        font2.setUnderline(false);
        pairNo->setFont(font2);
        pairNo->setSmallDecimalPoint(false);
        pairNo->setDigitCount(3);
        label_49 = new QLabel(centralWidget);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(1180, 10, 121, 31));
        label_49->setAlignment(Qt::AlignCenter);
        label_50 = new QLabel(centralWidget);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(1440, 10, 101, 31));
        label_50->setAlignment(Qt::AlignCenter);
        equalBoxTouch = new QCheckBox(centralWidget);
        equalBoxTouch->setObjectName(QStringLiteral("equalBoxTouch"));
        equalBoxTouch->setGeometry(QRect(2120, 630, 131, 71));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(1890, 290, 171, 31));
        label_14->setFont(font);
        label_14->setAlignment(Qt::AlignCenter);
        stiff1Scale_show = new QLCDNumber(centralWidget);
        stiff1Scale_show->setObjectName(QStringLiteral("stiff1Scale_show"));
        stiff1Scale_show->setGeometry(QRect(1990, 350, 61, 31));
        stiff1Scale_show->setDigitCount(6);
        reverseBox = new QRadioButton(centralWidget);
        reverseBox->setObjectName(QStringLiteral("reverseBox"));
        reverseBox->setGeometry(QRect(1920, 630, 171, 31));
        label_51 = new QLabel(centralWidget);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(1690, 160, 131, 31));
        subject_no = new QSpinBox(centralWidget);
        subject_no->setObjectName(QStringLiteral("subject_no"));
        subject_no->setGeometry(QRect(1690, 200, 81, 51));
        QFont font3;
        font3.setPointSize(18);
        subject_no->setFont(font3);
        subject_no->setMaximum(99);
        subject_no->setSingleStep(1);
        subject_no->setValue(1);
        stiff2Scale_show = new QLCDNumber(centralWidget);
        stiff2Scale_show->setObjectName(QStringLiteral("stiff2Scale_show"));
        stiff2Scale_show->setGeometry(QRect(1990, 450, 61, 31));
        stiff2Scale_show->setDigitCount(6);
        text = new QTextBrowser(centralWidget);
        text->setObjectName(QStringLiteral("text"));
        text->setGeometry(QRect(1140, 470, 256, 192));
        Act1_show = new QLCDNumber(centralWidget);
        Act1_show->setObjectName(QStringLiteral("Act1_show"));
        Act1_show->setGeometry(QRect(1720, 510, 61, 31));
        Act1_show->setDigitCount(6);
        Act2_show = new QLCDNumber(centralWidget);
        Act2_show->setObjectName(QStringLiteral("Act2_show"));
        Act2_show->setGeometry(QRect(1800, 510, 61, 31));
        Act2_show->setDigitCount(6);
        Act2 = new QSlider(centralWidget);
        Act2->setObjectName(QStringLiteral("Act2"));
        Act2->setGeometry(QRect(1810, 580, 16, 101));
        Act2->setMinimum(0);
        Act2->setMaximum(9);
        Act2->setSingleStep(1);
        Act2->setPageStep(10);
        Act2->setValue(0);
        Act2->setSliderPosition(0);
        Act2->setOrientation(Qt::Vertical);
        Act2->setTickPosition(QSlider::NoTicks);
        label_54 = new QLabel(centralWidget);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(1730, 550, 51, 21));
        label_54->setAlignment(Qt::AlignCenter);
        Act1 = new QSlider(centralWidget);
        Act1->setObjectName(QStringLiteral("Act1"));
        Act1->setGeometry(QRect(1750, 580, 16, 101));
        Act1->setMinimum(0);
        Act1->setMaximum(90);
        Act1->setSingleStep(1);
        Act1->setPageStep(10);
        Act1->setValue(0);
        Act1->setSliderPosition(0);
        Act1->setOrientation(Qt::Vertical);
        Act1->setTickPosition(QSlider::NoTicks);
        label_55 = new QLabel(centralWidget);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(1790, 550, 51, 21));
        label_55->setAlignment(Qt::AlignCenter);
        ForZ0 = new QLCDNumber(centralWidget);
        ForZ0->setObjectName(QStringLiteral("ForZ0"));
        ForZ0->setGeometry(QRect(1280, 90, 64, 23));
        ForZ0->setDigitCount(6);
        ForY0 = new QLCDNumber(centralWidget);
        ForY0->setObjectName(QStringLiteral("ForY0"));
        ForY0->setGeometry(QRect(1210, 90, 64, 23));
        ForY0->setDigitCount(6);
        ForX0 = new QLCDNumber(centralWidget);
        ForX0->setObjectName(QStringLiteral("ForX0"));
        ForX0->setGeometry(QRect(1140, 90, 64, 23));
        ForX0->setDigitCount(6);
        Manual = new QPushButton(centralWidget);
        Manual->setObjectName(QStringLiteral("Manual"));
        Manual->setGeometry(QRect(2000, 220, 151, 51));
        direction = new QLCDNumber(centralWidget);
        direction->setObjectName(QStringLiteral("direction"));
        direction->setGeometry(QRect(1140, 420, 61, 31));
        direction->setDigitCount(6);
        ForY1 = new QLCDNumber(centralWidget);
        ForY1->setObjectName(QStringLiteral("ForY1"));
        ForY1->setGeometry(QRect(1460, 90, 64, 23));
        ForY1->setDigitCount(6);
        ForX1 = new QLCDNumber(centralWidget);
        ForX1->setObjectName(QStringLiteral("ForX1"));
        ForX1->setGeometry(QRect(1390, 90, 64, 23));
        ForX1->setDigitCount(6);
        ForZ1 = new QLCDNumber(centralWidget);
        ForZ1->setObjectName(QStringLiteral("ForZ1"));
        ForZ1->setGeometry(QRect(1530, 90, 64, 23));
        ForZ1->setDigitCount(6);
        label_52 = new QLabel(centralWidget);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(1140, 50, 231, 31));
        label_53 = new QLabel(centralWidget);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(1140, 126, 211, 20));
        ForY0_2 = new QLCDNumber(centralWidget);
        ForY0_2->setObjectName(QStringLiteral("ForY0_2"));
        ForY0_2->setGeometry(QRect(1210, 150, 64, 23));
        ForY0_2->setDigitCount(6);
        ForX0_2 = new QLCDNumber(centralWidget);
        ForX0_2->setObjectName(QStringLiteral("ForX0_2"));
        ForX0_2->setGeometry(QRect(1140, 150, 64, 23));
        ForX0_2->setDigitCount(6);
        ForX1_2 = new QLCDNumber(centralWidget);
        ForX1_2->setObjectName(QStringLiteral("ForX1_2"));
        ForX1_2->setGeometry(QRect(1390, 150, 64, 23));
        ForX1_2->setDigitCount(6);
        ForZ0_2 = new QLCDNumber(centralWidget);
        ForZ0_2->setObjectName(QStringLiteral("ForZ0_2"));
        ForZ0_2->setGeometry(QRect(1280, 150, 64, 23));
        ForZ0_2->setDigitCount(6);
        ForZ1_2 = new QLCDNumber(centralWidget);
        ForZ1_2->setObjectName(QStringLiteral("ForZ1_2"));
        ForZ1_2->setGeometry(QRect(1530, 150, 64, 23));
        ForZ1_2->setDigitCount(6);
        ForY1_2 = new QLCDNumber(centralWidget);
        ForY1_2->setObjectName(QStringLiteral("ForY1_2"));
        ForY1_2->setGeometry(QRect(1460, 150, 64, 23));
        ForY1_2->setDigitCount(6);
        mass1_show = new QLCDNumber(centralWidget);
        mass1_show->setObjectName(QStringLiteral("mass1_show"));
        mass1_show->setGeometry(QRect(1900, 350, 61, 31));
        mass1_show->setDigitCount(6);
        mass2_show = new QLCDNumber(centralWidget);
        mass2_show->setObjectName(QStringLiteral("mass2_show"));
        mass2_show->setGeometry(QRect(1900, 450, 61, 31));
        mass2_show->setDigitCount(6);
        equalBox = new QRadioButton(centralWidget);
        equalBox->setObjectName(QStringLiteral("equalBox"));
        equalBox->setGeometry(QRect(2120, 580, 111, 51));
        StiffnMassCombined = new QPushButton(centralWidget);
        StiffnMassCombined->setObjectName(QStringLiteral("StiffnMassCombined"));
        StiffnMassCombined->setGeometry(QRect(2090, 120, 181, 91));
        SetTrialNo = new QSpinBox(centralWidget);
        SetTrialNo->setObjectName(QStringLiteral("SetTrialNo"));
        SetTrialNo->setGeometry(QRect(1630, 370, 81, 51));
        SetTrialNo->setFont(font3);
        SetTrialNo->setMaximum(99);
        SetTrialNo->setSingleStep(1);
        SetTrialNo->setValue(1);
        label_56 = new QLabel(centralWidget);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(1630, 330, 101, 41));
        AdjustTrialNo = new QCheckBox(centralWidget);
        AdjustTrialNo->setObjectName(QStringLiteral("AdjustTrialNo"));
        AdjustTrialNo->setGeometry(QRect(1730, 370, 131, 51));
        FingerMappingExp = new QPushButton(centralWidget);
        FingerMappingExp->setObjectName(QStringLiteral("FingerMappingExp"));
        FingerMappingExp->setGeometry(QRect(2090, 10, 181, 91));
        label_57 = new QLabel(centralWidget);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(1390, 50, 221, 31));
        label_58 = new QLabel(centralWidget);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(1390, 125, 211, 21));
        Condition1 = new QRadioButton(centralWidget);
        Condition1->setObjectName(QStringLiteral("Condition1"));
        Condition1->setGeometry(QRect(1470, 420, 121, 31));
        condition = new QLCDNumber(centralWidget);
        condition->setObjectName(QStringLiteral("condition"));
        condition->setGeometry(QRect(1390, 420, 61, 31));
        condition->setDigitCount(6);
        label_36 = new QLabel(centralWidget);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(1140, 370, 111, 51));
        label_36->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_37 = new QLabel(centralWidget);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(1390, 370, 171, 51));
        label_37->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(1900, 320, 61, 31));
        QFont font4;
        font4.setPointSize(10);
        label_16->setFont(font4);
        label_16->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(1980, 320, 81, 31));
        label_17->setFont(font4);
        label_17->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(1980, 420, 81, 31));
        label_18->setFont(font4);
        label_18->setAlignment(Qt::AlignCenter);
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(1890, 390, 171, 31));
        label_15->setFont(font);
        label_15->setAlignment(Qt::AlignCenter);
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(1900, 420, 61, 31));
        label_25->setFont(font4);
        label_25->setAlignment(Qt::AlignCenter);
        mappingTextBox = new QTextBrowser(centralWidget);
        mappingTextBox->setObjectName(QStringLiteral("mappingTextBox"));
        mappingTextBox->setGeometry(QRect(1450, 470, 241, 91));
        MainWindow->setCentralWidget(centralWidget);
        widget->raise();
        label_20->raise();
        label_67->raise();
        label_64->raise();
        label_19->raise();
        trialNo->raise();
        label_23->raise();
        DesZ0->raise();
        VRControl->raise();
        label_21->raise();
        label_24->raise();
        label_59->raise();
        label->raise();
        dynamicEnvironment->raise();
        lcdNumberHapticRate->raise();
        turnOff->raise();
        DesY0->raise();
        label_69->raise();
        label_22->raise();
        DesX1->raise();
        DesZ1->raise();
        DesY1->raise();
        DesX0->raise();
        placeHolder->raise();
        lcdNumberGraphicsRate->raise();
        label_31->raise();
        JakeRenderCheckBox->raise();
        label_11->raise();
        inertiaValue->raise();
        label_32->raise();
        cd_ratio->raise();
        CD_Vertical_Box->raise();
        StiffnessExp->raise();
        label_35->raise();
        mass_set->raise();
        MotorLCD_1->raise();
        StrokeLCD1_1->raise();
        label_27->raise();
        StrokeLCD1_0->raise();
        label_26->raise();
        MotorLCD_0->raise();
        pairNo->raise();
        label_49->raise();
        label_50->raise();
        equalBoxTouch->raise();
        label_14->raise();
        stiff1Scale_show->raise();
        reverseBox->raise();
        label_51->raise();
        subject_no->raise();
        stiff2Scale_show->raise();
        text->raise();
        Act1_show->raise();
        Act2_show->raise();
        Act2->raise();
        label_54->raise();
        Act1->raise();
        label_55->raise();
        ForZ0->raise();
        ForY0->raise();
        ForX0->raise();
        Manual->raise();
        direction->raise();
        ForY1->raise();
        ForX1->raise();
        ForZ1->raise();
        label_52->raise();
        label_53->raise();
        ForY0_2->raise();
        ForX0_2->raise();
        ForX1_2->raise();
        ForZ0_2->raise();
        ForZ1_2->raise();
        ForY1_2->raise();
        mass1_show->raise();
        mass2_show->raise();
        equalBox->raise();
        StiffnMassCombined->raise();
        SetTrialNo->raise();
        label_56->raise();
        AdjustTrialNo->raise();
        FingerMappingExp->raise();
        label_57->raise();
        label_58->raise();
        Condition1->raise();
        condition->raise();
        label_36->raise();
        label_37->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        label_15->raise();
        label_25->raise();
        mappingTextBox->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 2300, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "CHAI3D Haptics Environment -- OG", 0));
        label_20->setText(QApplication::translate("MainWindow", "Des Y", 0));
        label_67->setText(QApplication::translate("MainWindow", "Des Y", 0));
        label_64->setText(QApplication::translate("MainWindow", "Des X", 0));
        label_19->setText(QApplication::translate("MainWindow", "Des X", 0));
        label_23->setText(QApplication::translate("MainWindow", "Trial No.", 0));
        VRControl->setText(QApplication::translate("MainWindow", "VR\n"
"Control", 0));
        label_21->setText(QApplication::translate("MainWindow", "Des Z", 0));
        label_24->setText(QApplication::translate("MainWindow", "Pair No.", 0));
        label_59->setText(QApplication::translate("MainWindow", "Sensor", 0));
        label->setText(QApplication::translate("MainWindow", "Index Pot", 0));
        dynamicEnvironment->setText(QApplication::translate("MainWindow", "Dynamic\n"
"Bodies", 0));
        turnOff->setText(QApplication::translate("MainWindow", "Turn Off", 0));
        label_69->setText(QApplication::translate("MainWindow", "Des Z", 0));
        label_22->setText(QApplication::translate("MainWindow", "Haptic\n"
"Rate:", 0));
        label_34->setText(QApplication::translate("MainWindow", "Inertia", 0));
        label_12->setText(QApplication::translate("MainWindow", "Mass", 0));
        label_33->setText(QApplication::translate("MainWindow", "CD", 0));
        label_31->setText(QApplication::translate("MainWindow", "Graphics\n"
"Rate:", 0));
        JakeRenderCheckBox->setText(QApplication::translate("MainWindow", "JakeRender", 0));
        label_11->setText(QApplication::translate("MainWindow", "Scaled\n"
"Gravity", 0));
        label_32->setText(QApplication::translate("MainWindow", "CD Ratio", 0));
        CD_Vertical_Box->setText(QApplication::translate("MainWindow", "CD Vertical", 0));
        StiffnessExp->setText(QApplication::translate("MainWindow", "Stiffness\n"
"Experiment", 0));
        label_35->setText(QApplication::translate("MainWindow", "Mass", 0));
        label_27->setText(QApplication::translate("MainWindow", "Desired", 0));
        label_26->setText(QApplication::translate("MainWindow", "Desired", 0));
        label_49->setText(QApplication::translate("MainWindow", "INDEX", 0));
        label_50->setText(QApplication::translate("MainWindow", "THUMB", 0));
        equalBoxTouch->setText(QApplication::translate("MainWindow", "Touch\n"
"Effective", 0));
        label_14->setText(QApplication::translate("MainWindow", "Box1", 0));
        reverseBox->setText(QApplication::translate("MainWindow", "Reverse", 0));
        label_51->setText(QApplication::translate("MainWindow", "Subject No.", 0));
        label_54->setText(QApplication::translate("MainWindow", "Act1", 0));
        label_55->setText(QApplication::translate("MainWindow", "Act2", 0));
        Manual->setText(QApplication::translate("MainWindow", "Manual", 0));
        label_52->setText(QApplication::translate("MainWindow", "Stiffness Forces:", 0));
        label_53->setText(QApplication::translate("MainWindow", "Mass Forces:", 0));
        equalBox->setText(QApplication::translate("MainWindow", "Equal", 0));
        StiffnMassCombined->setText(QApplication::translate("MainWindow", "Stiffness-Mass\n"
"Experiment", 0));
        label_56->setText(QApplication::translate("MainWindow", "Trial No.", 0));
        AdjustTrialNo->setText(QApplication::translate("MainWindow", "Adjust\n"
"Trial No.", 0));
        FingerMappingExp->setText(QApplication::translate("MainWindow", "Finger Mapping\n"
"Experiment", 0));
        label_57->setText(QApplication::translate("MainWindow", "Stiffness Forces:", 0));
        label_58->setText(QApplication::translate("MainWindow", "Mass Forces:", 0));
        Condition1->setText(QApplication::translate("MainWindow", "Cond1", 0));
        label_36->setText(QApplication::translate("MainWindow", "Direction:", 0));
        label_37->setText(QApplication::translate("MainWindow", "Condtion No.:", 0));
        label_16->setText(QApplication::translate("MainWindow", "Mass", 0));
        label_17->setText(QApplication::translate("MainWindow", "Stiffness", 0));
        label_18->setText(QApplication::translate("MainWindow", "Stiffness", 0));
        label_15->setText(QApplication::translate("MainWindow", "Box2", 0));
        label_25->setText(QApplication::translate("MainWindow", "Mass", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_OG_H
